// ---------------------------------------------------------------------------
// Chat Feature — Mock Data
// Kiptra AI — Kitchen & Bath Design Platform
// ---------------------------------------------------------------------------

import type {
  ChatMember,
  ChatChannel,
  ChatMessage,
  TextMessage,
  SystemMessage,
  FileMessage,
  ChatIntegration,
  ChatReaction,
  ChatAttachment,
} from "@/lib/chat-types";

// ---------------------------------------------------------------------------
// Members
// ---------------------------------------------------------------------------

export const MOCK_MEMBERS: ChatMember[] = [
  {
    id: "current-user",
    name: "Alex Rivera",
    initials: "AR",
    role: "owner",
    platform: "kiptra",
    isOnline: true,
  },
  {
    id: "sarah-chen",
    name: "Sarah Chen",
    initials: "SC",
    role: "designer",
    platform: "slack",
    isOnline: true,
  },
  {
    id: "mike-thompson",
    name: "Mike Thompson",
    initials: "MT",
    role: "contractor",
    platform: "teams",
    isOnline: true,
  },
  {
    id: "jason-park",
    name: "Jason Park",
    initials: "JP",
    role: "contractor",
    platform: "slack",
    isOnline: false,
    lastSeen: "2026-03-24T15:30:00Z",
  },
  {
    id: "lisa-johnson",
    name: "Lisa Johnson",
    initials: "LJ",
    role: "homeowner",
    platform: "kiptra",
    isOnline: false,
    lastSeen: "2026-03-24T12:15:00Z",
  },
  {
    id: "david-kim",
    name: "David Kim",
    initials: "DK",
    role: "dealer",
    platform: "teams",
    isOnline: true,
  },
  {
    id: "rachel-torres",
    name: "Rachel Torres",
    initials: "RT",
    role: "designer",
    platform: "slack",
    isOnline: true,
  },
  {
    id: "carlos-mendez",
    name: "Carlos Mendez",
    initials: "CM",
    role: "contractor",
    platform: "slack",
    isOnline: false,
    lastSeen: "2026-03-24T14:00:00Z",
  },
  {
    id: "emma-walsh",
    name: "Emma Walsh",
    initials: "EW",
    role: "rep",
    platform: "teams",
    isOnline: true,
  },
  {
    id: "tom-bradley",
    name: "Tom Bradley",
    initials: "TB",
    role: "contractor",
    platform: "slack",
    isOnline: false,
    lastSeen: "2026-03-24T11:45:00Z",
  },
  {
    id: "kiptra-ai",
    name: "Kiptra AI",
    initials: "KA",
    role: "admin",
    platform: "kiptra",
    isOnline: true,
  },
];

// Helpers to grab members by ID
const m = (id: string): ChatMember =>
  MOCK_MEMBERS.find((x) => x.id === id)!;

// ---------------------------------------------------------------------------
// Channels
// ---------------------------------------------------------------------------

export const MOCK_CHANNELS: ChatChannel[] = [
  {
    id: "proj-smith-kitchen",
    name: "proj-smith-kitchen",
    displayName: "Smith Kitchen Remodel",
    type: "project",
    projectId: "proj-smith-001",
    platform: "slack",
    slackChannelId: "C07SMITH01",
    members: [m("current-user"), m("sarah-chen"), m("mike-thompson"), m("jason-park"), m("lisa-johnson"), m("carlos-mendez")],
    unreadCount: 3,
    isArchived: false,
    isMuted: false,
    topic: '36" island, KraftMaid Shaker, quartz counters',
    createdAt: "2026-02-10T09:00:00Z",
  },
  {
    id: "proj-johnson-masterbath",
    name: "proj-johnson-masterbath",
    displayName: "Johnson Master Bath",
    type: "project",
    projectId: "proj-johnson-002",
    platform: "teams",
    teamsChannelId: "19:johnson-bath@thread",
    members: [m("current-user"), m("rachel-torres"), m("mike-thompson"), m("david-kim")],
    unreadCount: 0,
    isArchived: false,
    isMuted: false,
    topic: "Walk-in shower conversion, heated floors",
    createdAt: "2026-02-18T14:00:00Z",
  },
  {
    id: "proj-garcia-fullremodel",
    name: "proj-garcia-fullremodel",
    displayName: "Garcia Full Remodel",
    type: "project",
    projectId: "proj-garcia-003",
    platform: "slack",
    slackChannelId: "C07GARCIA01",
    members: [m("current-user"), m("sarah-chen"), m("mike-thompson"), m("jason-park"), m("rachel-torres"), m("carlos-mendez"), m("tom-bradley"), m("david-kim")],
    unreadCount: 7,
    isArchived: false,
    isMuted: false,
    topic: "Phase 2: Kitchen demo starts Mar 28",
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "general",
    name: "general",
    displayName: "General",
    type: "general",
    platform: "slack",
    slackChannelId: "C07GENERAL",
    members: MOCK_MEMBERS,
    unreadCount: 1,
    isArchived: false,
    isMuted: false,
    createdAt: "2025-06-01T09:00:00Z",
  },
  {
    id: "submittals",
    name: "submittals",
    displayName: "Submittals",
    type: "general",
    platform: "slack",
    slackChannelId: "C07SUBMIT",
    members: [m("current-user"), m("sarah-chen"), m("david-kim"), m("mike-thompson"), m("rachel-torres"), m("emma-walsh")],
    unreadCount: 2,
    isArchived: false,
    isMuted: false,
    createdAt: "2025-06-01T09:00:00Z",
  },
  {
    id: "installations",
    name: "installations",
    displayName: "Installations",
    type: "general",
    platform: "teams",
    teamsChannelId: "19:installations@thread",
    members: [m("current-user"), m("mike-thompson"), m("jason-park"), m("carlos-mendez"), m("tom-bradley")],
    unreadCount: 0,
    isArchived: false,
    isMuted: false,
    createdAt: "2025-06-01T09:00:00Z",
  },
  {
    id: "dm-sarah",
    name: "dm-sarah",
    displayName: "Sarah Chen",
    type: "dm",
    platform: "slack",
    slackChannelId: "D07SARAH",
    members: [m("current-user"), m("sarah-chen")],
    unreadCount: 1,
    isArchived: false,
    isMuted: false,
    createdAt: "2026-01-05T10:00:00Z",
  },
  {
    id: "dm-mike",
    name: "dm-mike",
    displayName: "Mike Thompson",
    type: "dm",
    platform: "teams",
    teamsChannelId: "19:dm-mike@thread",
    members: [m("current-user"), m("mike-thompson")],
    unreadCount: 0,
    isArchived: false,
    isMuted: false,
    createdAt: "2026-01-08T11:00:00Z",
  },
  {
    id: "dm-lisa",
    name: "dm-lisa",
    displayName: "Lisa Johnson",
    type: "dm",
    platform: "kiptra",
    members: [m("current-user"), m("lisa-johnson")],
    unreadCount: 2,
    isArchived: false,
    isMuted: false,
    createdAt: "2026-02-12T15:00:00Z",
  },
  {
    id: "gm-smith-team",
    name: "gm-smith-team",
    displayName: "Smith Kitchen Team",
    type: "group_dm",
    platform: "slack",
    slackChannelId: "G07SMITH",
    members: [m("current-user"), m("sarah-chen"), m("mike-thompson"), m("jason-park")],
    unreadCount: 0,
    isArchived: false,
    isMuted: false,
    createdAt: "2026-02-12T16:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Messages — #proj-smith-kitchen (22 messages)
// ---------------------------------------------------------------------------

const smithKitchenMessages: ChatMessage[] = [
  {
    id: "sk-001",
    channelId: "proj-smith-kitchen",
    sender: m("sarah-chen"),
    source: "slack",
    type: "text",
    content: "Hey team, uploaded the final cabinet specs from KraftMaid. 42 uppers, Shaker style in Dove White. Take a look when you get a chance",
    mentions: [],
    attachments: [
      {
        id: "att-001",
        name: "KraftMaid_Shaker_DoveWhite_Specs.pdf",
        fileType: "pdf",
        url: "/files/kraftmaid-specs.pdf",
        size: "2.4 MB",
      },
    ],
    createdAt: "2026-03-22T09:15:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Alex Rivera", "Mike Thompson"], count: 2 }],
    readBy: ["current-user", "mike-thompson", "jason-park"],
    replyCount: 0,
  },
  {
    id: "sk-002",
    channelId: "proj-smith-kitchen",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "Got it. Plumbing rough-in is confirmed for Monday 3/25. My crew will be there by 7am. Need the island location finalized before then — are we still at 36\" from the south wall?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T09:42:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "sarah-chen"],
    replyCount: 0,
  },
  {
    id: "sk-003",
    channelId: "proj-smith-kitchen",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Yes, 36\" from south wall is locked. Sarah confirmed clearances work with the 30\" dishwasher. @Lisa Johnson — just a heads up, plumbing starts Monday so the kitchen will be out of commission for about 3 days",
    mentions: ["lisa-johnson"],
    attachments: [],
    createdAt: "2026-03-22T10:05:00Z",
    isEdited: false,
    reactions: [{ emoji: "✅", users: ["Mike Thompson"], count: 1 }],
    readBy: ["sarah-chen", "mike-thompson", "jason-park", "lisa-johnson"],
    replyCount: 0,
  },
  {
    id: "sk-004",
    channelId: "proj-smith-kitchen",
    sender: m("kiptra-ai"),
    source: "kiptra",
    type: "system",
    content: "✅ Milestone Complete: Demolition — All demo work signed off by inspector. Debris removal confirmed.",
    systemAction: "milestone_complete",
    createdAt: "2026-03-22T11:30:00Z",
    isEdited: false,
    reactions: [{ emoji: "🎉", users: ["Sarah Chen", "Alex Rivera"], count: 2 }],
    readBy: ["current-user", "sarah-chen", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "sk-005",
    channelId: "proj-smith-kitchen",
    sender: m("sarah-chen"),
    source: "slack",
    type: "text",
    content: "Quick question on the KraftMaid submittal — did we go with the W3630 or W3636 for the corner lazy susan? The quote has both listed",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T13:20:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "mike-thompson"],
    replyCount: 4,
    lastReplyAt: "2026-03-22T14:15:00Z",
  },
  {
    id: "sk-006",
    channelId: "proj-smith-kitchen",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "W3636. The 30\" was too tight with the filler panel. I updated the submittal already",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T14:10:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["sarah-chen", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "sk-007",
    channelId: "proj-smith-kitchen",
    sender: m("carlos-mendez"),
    source: "slack",
    type: "text",
    content: "Hey Alex, quick q — is the gas line for the range coming from the basement or is there an existing stub behind the wall? Want to plan my materials before Monday",
    mentions: ["current-user"],
    attachments: [],
    createdAt: "2026-03-22T15:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "sk-008",
    channelId: "proj-smith-kitchen",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "There's an existing 1/2\" stub behind the drywall on the east wall, about 18\" off the floor. Should be straightforward. I'll mark it on the site Friday",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T15:12:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Carlos Mendez"], count: 1 }],
    readBy: ["carlos-mendez", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "sk-009",
    channelId: "proj-smith-kitchen",
    sender: m("kiptra-ai"),
    source: "kiptra",
    type: "system",
    content: "📋 Change Order #CO-2026-014 created: Add under-cabinet LED lighting — $1,200 (labor + materials). Awaiting homeowner approval.",
    systemAction: "change_order_created",
    createdAt: "2026-03-22T16:30:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "sarah-chen"],
    replyCount: 0,
  },
  {
    id: "sk-010",
    channelId: "proj-smith-kitchen",
    sender: m("lisa-johnson"),
    source: "kiptra",
    type: "text",
    content: "Hi Alex! Thanks for the heads up about Monday. We'll plan to eat out 😊 Also saw the change order for the LED lights — yes please, approved!",
    mentions: ["current-user"],
    attachments: [],
    createdAt: "2026-03-22T18:45:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Alex Rivera"], count: 1 }],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "sk-011",
    channelId: "proj-smith-kitchen",
    sender: m("jason-park"),
    source: "slack",
    type: "text",
    content: "Cabinets delivered to the shop. All 28 boxes accounted for, no damage. KraftMaid Shaker Dove White. Storing in bay 3 until install day",
    mentions: [],
    attachments: [
      {
        id: "att-002",
        name: "delivery_receipt_kraftmaid.pdf",
        fileType: "pdf",
        url: "/files/delivery-receipt.pdf",
        size: "340 KB",
      },
    ],
    createdAt: "2026-03-23T08:30:00Z",
    isEdited: false,
    reactions: [{ emoji: "✅", users: ["Alex Rivera", "Sarah Chen"], count: 2 }],
    readBy: ["current-user", "sarah-chen", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "sk-012",
    channelId: "proj-smith-kitchen",
    sender: m("kiptra-ai"),
    source: "kiptra",
    type: "system",
    content: "📦 Delivery Confirmed: KraftMaid cabinet order (28 units) received at Rivera Remodeling warehouse.",
    systemAction: "delivery_scheduled",
    createdAt: "2026-03-23T08:31:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "sk-013",
    channelId: "proj-smith-kitchen",
    sender: m("sarah-chen"),
    source: "slack",
    type: "text",
    content: "Perfect timing on the cabinets. Countertop template is scheduled for Thursday after the uppers are set. MSI Calacatta Laza quartz — 3cm with eased edge. Fabricator needs 8 business days after template",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T09:15:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "sk-014",
    channelId: "proj-smith-kitchen",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "8 days is tight if we want to hit the Apr 15 punch list. Can we push the templating to Wednesday to buy a day?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T09:30:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "sarah-chen"],
    replyCount: 0,
  },
  {
    id: "sk-015",
    channelId: "proj-smith-kitchen",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Let's keep Thursday for template. If we need the extra day we can push punch list to Apr 16. I'd rather not rush the upper install",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T09:45:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Mike Thompson", "Sarah Chen"], count: 2 }],
    readBy: ["sarah-chen", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "sk-016",
    channelId: "proj-smith-kitchen",
    sender: m("carlos-mendez"),
    source: "slack",
    type: "text",
    content: "FYI — picked up the SharkBite fittings and the new angle stops for the Smith job. Total was $285. Receipt attached",
    mentions: [],
    attachments: [
      {
        id: "att-003",
        name: "plumbing_supplies_receipt.pdf",
        fileType: "pdf",
        url: "/files/plumbing-receipt.pdf",
        size: "180 KB",
      },
    ],
    createdAt: "2026-03-23T11:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "sk-017",
    channelId: "proj-smith-kitchen",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "Backsplash tile is in at the distributor. 4x12 white subway, Daltile Rittenhouse. 15 boxes. Jason can you grab those tomorrow?",
    mentions: ["jason-park"],
    attachments: [],
    createdAt: "2026-03-23T14:20:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "jason-park"],
    replyCount: 0,
  },
  {
    id: "sk-018",
    channelId: "proj-smith-kitchen",
    sender: m("jason-park"),
    source: "slack",
    type: "text",
    content: "Yep I'll swing by first thing. They open at 7 right?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T14:35:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "sk-019",
    channelId: "proj-smith-kitchen",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "7:30. Ask for Ray at the counter, he's got it set aside",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T14:38:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Jason Park"], count: 1 }],
    readBy: ["current-user", "jason-park"],
    replyCount: 0,
  },
  {
    id: "sk-020",
    channelId: "proj-smith-kitchen",
    sender: m("sarah-chen"),
    source: "slack",
    type: "file",
    content: "Updated layout with the final appliance locations. Fridge recess is 36\", range is 30\". Sink centered on the window.",
    attachments: [
      {
        id: "att-004",
        name: "Smith_Kitchen_Layout_v4.pdf",
        fileType: "pdf",
        url: "/files/smith-layout-v4.pdf",
        size: "1.8 MB",
        thumbnailUrl: "/thumbs/smith-layout-v4.png",
      },
    ],
    createdAt: "2026-03-24T08:00:00Z",
    isEdited: false,
    reactions: [{ emoji: "✅", users: ["Alex Rivera"], count: 1 }],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "sk-021",
    channelId: "proj-smith-kitchen",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Looks good Sarah. Mike — can you confirm the sink drain aligns with what's roughed in? Don't want any surprises Monday",
    mentions: ["mike-thompson"],
    attachments: [],
    createdAt: "2026-03-24T08:15:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["sarah-chen"],
    replyCount: 0,
  },
  {
    id: "sk-022",
    channelId: "proj-smith-kitchen",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "Checking now. The existing drain is 14\" off center to the left. We may need to offset the P-trap. I'll confirm after I measure tonight",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-24T08:45:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "sarah-chen"],
    replyCount: 0,
  },
];

// ---------------------------------------------------------------------------
// Messages — #proj-johnson-masterbath (10 messages)
// ---------------------------------------------------------------------------

const johnsonBathMessages: ChatMessage[] = [
  {
    id: "jb-001",
    channelId: "proj-johnson-masterbath",
    sender: m("rachel-torres"),
    source: "slack",
    type: "file",
    content: "Here are the two render options for the shower niche. Option A has the horizontal accent band at 48\", Option B at 60\". I think A reads better with the 8' ceiling",
    attachments: [
      {
        id: "att-010",
        name: "Johnson_ShowerNiche_OptionA.png",
        fileType: "design_render",
        url: "/files/johnson-niche-a.png",
        size: "3.1 MB",
        thumbnailUrl: "/thumbs/johnson-niche-a.png",
      },
      {
        id: "att-011",
        name: "Johnson_ShowerNiche_OptionB.png",
        fileType: "design_render",
        url: "/files/johnson-niche-b.png",
        size: "2.9 MB",
        thumbnailUrl: "/thumbs/johnson-niche-b.png",
      },
    ],
    createdAt: "2026-03-22T10:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "mike-thompson", "david-kim"],
    replyCount: 0,
  },
  {
    id: "jb-002",
    channelId: "proj-johnson-masterbath",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Option A for sure. The 48\" line ties in nicely with the vanity backsplash height too. Rachel can you mock up the full wall elevation with that?",
    mentions: ["rachel-torres"],
    attachments: [],
    createdAt: "2026-03-22T10:20:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Rachel Torres"], count: 1 }],
    readBy: ["rachel-torres", "mike-thompson", "david-kim"],
    replyCount: 0,
  },
  {
    id: "jb-003",
    channelId: "proj-johnson-masterbath",
    sender: m("david-kim"),
    source: "teams",
    type: "text",
    content: "Tile selection thread — we're between the Emser Palazzo Avorio 12x24 and the Florida Tile Streamline Arctic. Palazzo is $6.85/sf, Streamline is $4.20/sf. Lead time on Palazzo is 3 weeks though",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T11:30:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "rachel-torres", "mike-thompson"],
    replyCount: 3,
    lastReplyAt: "2026-03-22T13:00:00Z",
  },
  {
    id: "jb-004",
    channelId: "proj-johnson-masterbath",
    sender: m("kiptra-ai"),
    source: "kiptra",
    type: "system",
    content: "📋 Submittal #SUB-2026-031 created: Delta Trinsic 14\" shower system (matte black) — $1,450. Sent to homeowner for approval.",
    systemAction: "submittal_created",
    createdAt: "2026-03-22T14:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "david-kim"],
    replyCount: 0,
  },
  {
    id: "jb-005",
    channelId: "proj-johnson-masterbath",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "For the heated floor — I need the WarmlyYours TempZone mats ordered by end of week. 62 sq ft. The thinset needs 24hr cure before tile so that pushes install to Wednesday at earliest",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T08:15:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "rachel-torres"],
    replyCount: 0,
  },
  {
    id: "jb-006",
    channelId: "proj-johnson-masterbath",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "David — can you get the WarmlyYours quote today? 62 sq ft TempZone, 120V. Need the thermostat too, the programmable one",
    mentions: ["david-kim"],
    attachments: [],
    createdAt: "2026-03-23T08:30:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["david-kim", "mike-thompson", "rachel-torres"],
    replyCount: 0,
  },
  {
    id: "jb-007",
    channelId: "proj-johnson-masterbath",
    sender: m("david-kim"),
    source: "teams",
    type: "text",
    content: "On it. TempZone 62sf + nSpiration programmable thermostat. Looking at $845 for the mat and $189 for the thermostat. Can ship overnight for $35 extra. Want me to pull the trigger?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T10:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "jb-008",
    channelId: "proj-johnson-masterbath",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Yes, do the overnight. Worth $35 to keep the schedule. Thanks David",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T10:10:00Z",
    isEdited: false,
    reactions: [{ emoji: "✅", users: ["David Kim"], count: 1 }],
    readBy: ["david-kim", "mike-thompson", "rachel-torres"],
    replyCount: 0,
  },
  {
    id: "jb-009",
    channelId: "proj-johnson-masterbath",
    sender: m("rachel-torres"),
    source: "slack",
    type: "file",
    content: "Full wall elevation with Option A niche. Also added the vanity mirror and sconce placement. Let me know if the sconce height works — I have them at 66\" AFF",
    attachments: [
      {
        id: "att-012",
        name: "Johnson_Bath_WallElevation_v2.pdf",
        fileType: "design_render",
        url: "/files/johnson-elevation-v2.pdf",
        size: "4.2 MB",
        thumbnailUrl: "/thumbs/johnson-elevation-v2.png",
      },
    ],
    createdAt: "2026-03-23T15:30:00Z",
    isEdited: false,
    reactions: [{ emoji: "🔥", users: ["Alex Rivera", "David Kim"], count: 2 }],
    readBy: ["current-user", "david-kim", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "jb-010",
    channelId: "proj-johnson-masterbath",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "66\" for sconces is perfect. I'll have the electrician pre-wire those boxes at the same time as the heated floor connection. Two birds one stone",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T16:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "rachel-torres"],
    replyCount: 0,
  },
];

// ---------------------------------------------------------------------------
// Messages — #proj-garcia-fullremodel (15 messages)
// ---------------------------------------------------------------------------

const garciaMessages: ChatMessage[] = [
  {
    id: "gr-001",
    channelId: "proj-garcia-fullremodel",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Team — Phase 1 bath is wrapping up this week. Phase 2 kitchen demo starts Friday 3/28. Mike, make sure we have the dumpster scheduled",
    mentions: ["mike-thompson"],
    attachments: [],
    createdAt: "2026-03-22T08:00:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Mike Thompson"], count: 1 }],
    readBy: ["mike-thompson", "sarah-chen", "rachel-torres"],
    replyCount: 0,
  },
  {
    id: "gr-002",
    channelId: "proj-garcia-fullremodel",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "Dumpster is confirmed. 30-yard, arrives Thursday evening. Also — the Garcias asked about adding a pot filler above the range. That's not in scope, right?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T08:30:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "sarah-chen"],
    replyCount: 0,
  },
  {
    id: "gr-003",
    channelId: "proj-garcia-fullremodel",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Not in scope. I'll write up a change order — the plumbing run to the range wall is going to add $850-1,100 depending on where Carlos can tie in. Plus the fixture itself",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T08:45:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["mike-thompson", "sarah-chen", "carlos-mendez"],
    replyCount: 0,
  },
  {
    id: "gr-004",
    channelId: "proj-garcia-fullremodel",
    sender: m("kiptra-ai"),
    source: "kiptra",
    type: "system",
    content: "⚠️ Material Backordered: Caesarstone Calacatta Maximus (5143) — ETA pushed to April 14. Current project date: April 8.",
    systemAction: "delivery_scheduled",
    createdAt: "2026-03-22T10:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "sarah-chen", "david-kim"],
    replyCount: 3,
    lastReplyAt: "2026-03-22T11:15:00Z",
  },
  {
    id: "gr-005",
    channelId: "proj-garcia-fullremodel",
    sender: m("sarah-chen"),
    source: "slack",
    type: "text",
    content: "That backorder is going to blow up our timeline. David — is there an alternative in the Caesarstone line that's in stock? Maybe the 5141 or 5153?",
    mentions: ["david-kim"],
    attachments: [],
    createdAt: "2026-03-22T10:15:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "david-kim"],
    replyCount: 0,
  },
  {
    id: "gr-006",
    channelId: "proj-garcia-fullremodel",
    sender: m("david-kim"),
    source: "teams",
    type: "text",
    content: "5141 Frosty Carrina is in stock locally. Similar look, slightly cooler veining. $78/sf vs $82/sf for the Maximus. I can get a sample to the Garcias by tomorrow",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T10:45:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Sarah Chen", "Alex Rivera"], count: 2 }],
    readBy: ["current-user", "sarah-chen"],
    replyCount: 0,
  },
  {
    id: "gr-007",
    channelId: "proj-garcia-fullremodel",
    sender: m("tom-bradley"),
    source: "slack",
    type: "text",
    content: "Question about the Garcia kitchen — the panel is 200A but they want the induction cooktop (50A) plus the double wall oven (50A) plus existing loads. I'm at about 185A total. We might need a panel upgrade or load calc to make this work",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T13:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "gr-008",
    channelId: "proj-garcia-fullremodel",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Tom — run the full load calc and let me know. If we need the upgrade, that's a separate permit and adds 2 weeks minimum. Better to know now than mid-install",
    mentions: ["tom-bradley"],
    attachments: [],
    createdAt: "2026-03-22T13:15:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Tom Bradley"], count: 1 }],
    readBy: ["tom-bradley", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "gr-009",
    channelId: "proj-garcia-fullremodel",
    sender: m("rachel-torres"),
    source: "slack",
    type: "text",
    content: "Updated the Garcia kitchen budget tracker. We're at $67,400 committed out of $75,000 budget. That leaves $7,600 for countertops, backsplash, and lighting. Tight but doable if we go with the Frosty Carrina",
    mentions: [],
    attachments: [
      {
        id: "att-020",
        name: "Garcia_Budget_Tracker_v3.xlsx",
        fileType: "spreadsheet",
        url: "/files/garcia-budget-v3.xlsx",
        size: "245 KB",
      },
    ],
    createdAt: "2026-03-23T09:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "sarah-chen"],
    replyCount: 0,
  },
  {
    id: "gr-010",
    channelId: "proj-garcia-fullremodel",
    sender: m("carlos-mendez"),
    source: "slack",
    type: "text",
    content: "Finished the bath rough-in inspection. Passed first try 👊 Moving to kitchen plumbing once demo is done Friday",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T10:30:00Z",
    isEdited: false,
    reactions: [{ emoji: "🎉", users: ["Alex Rivera", "Mike Thompson"], count: 2 }],
    readBy: ["current-user", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "gr-011",
    channelId: "proj-garcia-fullremodel",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "Nice work Carlos. Alex — I need 3 guys for the kitchen demo Friday. My usual crew is tied up on a commercial job. Can I pull from the Smith crew since they'll be waiting on countertops?",
    mentions: ["current-user"],
    attachments: [],
    createdAt: "2026-03-23T11:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "carlos-mendez"],
    replyCount: 0,
  },
  {
    id: "gr-012",
    channelId: "proj-garcia-fullremodel",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Yeah that works. Jason and two of his guys can handle it. Demo should be one long day if we start early",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T11:15:00Z",
    isEdited: false,
    reactions: [{ emoji: "✅", users: ["Mike Thompson"], count: 1 }],
    readBy: ["mike-thompson", "jason-park"],
    replyCount: 0,
  },
  {
    id: "gr-013",
    channelId: "proj-garcia-fullremodel",
    sender: m("sarah-chen"),
    source: "slack",
    type: "text",
    content: "Garcias approved the Frosty Carrina! Sending the PO to David now. 48 sf for perimeter + 22 sf for the island = 70 sf total. With waste factor call it 78 sf",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-24T09:00:00Z",
    isEdited: false,
    reactions: [{ emoji: "🎉", users: ["Alex Rivera"], count: 1 }],
    readBy: ["current-user", "david-kim"],
    replyCount: 0,
  },
  {
    id: "gr-014",
    channelId: "proj-garcia-fullremodel",
    sender: m("tom-bradley"),
    source: "slack",
    type: "text",
    content: "Load calc done. We're at 187A on a 200A panel. Technically within limits but no room for future loads. I'd recommend the panel upgrade to 320A — adds about $3,200 and needs a separate permit. Your call",
    mentions: [],
    attachments: [
      {
        id: "att-021",
        name: "Garcia_LoadCalc_Report.pdf",
        fileType: "pdf",
        url: "/files/garcia-loadcalc.pdf",
        size: "520 KB",
      },
    ],
    createdAt: "2026-03-24T10:30:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "gr-015",
    channelId: "proj-garcia-fullremodel",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Let's do the upgrade. 187A on a 200A panel with an induction top is asking for trouble. I'll talk to the Garcias about the cost — it's the right call for resale value too. Tom, start the permit app",
    mentions: ["tom-bradley"],
    attachments: [],
    createdAt: "2026-03-24T10:45:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Tom Bradley", "Mike Thompson"], count: 2 }],
    readBy: ["tom-bradley", "mike-thompson"],
    replyCount: 0,
  },
];

// ---------------------------------------------------------------------------
// Messages — #general (5 messages)
// ---------------------------------------------------------------------------

const generalMessages: ChatMessage[] = [
  {
    id: "gen-001",
    channelId: "general",
    sender: m("emma-walsh"),
    source: "teams",
    type: "text",
    content: "Hey everyone — KBIS 2026 in Vegas is confirmed for Oct 1-3. Early bird booth registration closes April 15. Should we get a booth this year? Last year's was amazing for leads",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T12:00:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Alex Rivera", "Sarah Chen", "Rachel Torres"], count: 3 }],
    readBy: ["current-user", "sarah-chen", "rachel-torres"],
    replyCount: 0,
  },
  {
    id: "gen-002",
    channelId: "general",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Definitely yes on KBIS. Emma can you get the pricing for a 10x10 inline? Last year was around $4,800 if I remember right",
    mentions: ["emma-walsh"],
    attachments: [],
    createdAt: "2026-03-22T12:15:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["emma-walsh", "sarah-chen"],
    replyCount: 0,
  },
  {
    id: "gen-003",
    channelId: "general",
    sender: m("emma-walsh"),
    source: "teams",
    type: "text",
    content: "Will do! Also — KraftMaid is doing a dealer appreciation dinner the night before. Free for top-tier partners. I'll get us on the list",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T12:30:00Z",
    isEdited: false,
    reactions: [{ emoji: "🔥", users: ["Alex Rivera"], count: 1 }],
    readBy: ["current-user", "sarah-chen"],
    replyCount: 0,
  },
  {
    id: "gen-004",
    channelId: "general",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Quick update — rolled out the new Kiptra scheduling feature. You can now see all project timelines in one calendar view. Check the left sidebar under \"Schedule\". Lmk if you hit any bugs",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T16:00:00Z",
    isEdited: false,
    reactions: [{ emoji: "🎉", users: ["Rachel Torres", "David Kim"], count: 2 }],
    readBy: ["sarah-chen", "rachel-torres", "mike-thompson", "david-kim"],
    replyCount: 0,
  },
  {
    id: "gen-005",
    channelId: "general",
    sender: m("rachel-torres"),
    source: "slack",
    type: "text",
    content: "The calendar view is great! One thing — can we color-code by project status? Active vs on-hold vs complete? Would make it easier to scan",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-24T09:30:00Z",
    isEdited: false,
    reactions: [{ emoji: "💡", users: ["Sarah Chen", "Alex Rivera"], count: 2 }],
    readBy: ["current-user"],
    replyCount: 0,
  },
];

// ---------------------------------------------------------------------------
// Messages — #submittals (8 messages)
// ---------------------------------------------------------------------------

const submittalsMessages: ChatMessage[] = [
  {
    id: "sub-001",
    channelId: "submittals",
    sender: m("kiptra-ai"),
    source: "kiptra",
    type: "system",
    content: "📋 Submittal #SUB-2026-028 created: KraftMaid Shaker Dove White cabinet package (28 units) — $28,500. Project: Smith Kitchen.",
    systemAction: "submittal_created",
    createdAt: "2026-03-22T09:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "sarah-chen", "david-kim"],
    replyCount: 0,
  },
  {
    id: "sub-002",
    channelId: "submittals",
    sender: m("david-kim"),
    source: "teams",
    type: "text",
    content: "SUB-028 pricing confirmed with KraftMaid rep. Lead time is 4-6 weeks standard. We ordered 3/1 so we're right on track for the 3/23 delivery",
    mentions: [],
    attachments: [
      {
        id: "att-030",
        name: "KraftMaid_PO_Confirmation.pdf",
        fileType: "pdf",
        url: "/files/kraftmaid-po.pdf",
        size: "890 KB",
      },
    ],
    createdAt: "2026-03-22T09:30:00Z",
    isEdited: false,
    reactions: [{ emoji: "✅", users: ["Alex Rivera"], count: 1 }],
    readBy: ["current-user", "sarah-chen"],
    replyCount: 0,
  },
  {
    id: "sub-003",
    channelId: "submittals",
    sender: m("kiptra-ai"),
    source: "kiptra",
    type: "system",
    content: "✅ Submittal #SUB-2026-028 APPROVED by Lisa Johnson (homeowner). KraftMaid cabinet package confirmed.",
    systemAction: "submittal_approved",
    createdAt: "2026-03-22T11:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "sarah-chen", "david-kim"],
    replyCount: 0,
  },
  {
    id: "sub-004",
    channelId: "submittals",
    sender: m("sarah-chen"),
    source: "slack",
    type: "text",
    content: "Submitting the MSI Calacatta Laza quartz for Smith kitchen. 3cm eased edge, 45 sf including island. Fabricator quote attached — $4,950 installed",
    mentions: [],
    attachments: [
      {
        id: "att-031",
        name: "MSI_Calacatta_Laza_Quote.pdf",
        fileType: "pdf",
        url: "/files/msi-quartz-quote.pdf",
        size: "1.2 MB",
      },
    ],
    createdAt: "2026-03-23T10:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "david-kim"],
    replyCount: 0,
  },
  {
    id: "sub-005",
    channelId: "submittals",
    sender: m("kiptra-ai"),
    source: "kiptra",
    type: "system",
    content: "📋 Submittal #SUB-2026-029 created: MSI Calacatta Laza quartz countertops — $4,950. Project: Smith Kitchen.",
    systemAction: "submittal_created",
    createdAt: "2026-03-23T10:05:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "sarah-chen"],
    replyCount: 0,
  },
  {
    id: "sub-006",
    channelId: "submittals",
    sender: m("emma-walsh"),
    source: "teams",
    type: "text",
    content: "Garcia project — need to swap the countertop submittal from Caesarstone 5143 to 5141 Frosty Carrina due to backorder. New quote is $6,084 for 78 sf at $78/sf. Rejecting the old one now",
    mentions: [],
    attachments: [
      {
        id: "att-032",
        name: "Caesarstone_5141_Revised_Quote.pdf",
        fileType: "pdf",
        url: "/files/caesarstone-revised.pdf",
        size: "780 KB",
      },
    ],
    createdAt: "2026-03-24T09:15:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "sub-007",
    channelId: "submittals",
    sender: m("kiptra-ai"),
    source: "kiptra",
    type: "system",
    content: "❌ Submittal #SUB-2026-025 REJECTED: Caesarstone 5143 Calacatta Maximus — Reason: Material backordered past project deadline.",
    systemAction: "submittal_rejected",
    createdAt: "2026-03-24T09:16:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "sub-008",
    channelId: "submittals",
    sender: m("kiptra-ai"),
    source: "kiptra",
    type: "system",
    content: "📋 Submittal #SUB-2026-032 created: Caesarstone 5141 Frosty Carrina quartz (78 sf) — $6,084. Project: Garcia Full Remodel.",
    systemAction: "submittal_created",
    createdAt: "2026-03-24T09:17:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user"],
    replyCount: 0,
  },
];

// ---------------------------------------------------------------------------
// Messages — #installations (5 messages)
// ---------------------------------------------------------------------------

const installationsMessages: ChatMessage[] = [
  {
    id: "inst-001",
    channelId: "installations",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "Install schedule for next week: Mon-Wed Smith upper cabinets, Thu Smith countertop template, Fri Garcia kitchen demo. Gonna be a full week",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T15:00:00Z",
    isEdited: false,
    reactions: [{ emoji: "💪", users: ["Jason Park"], count: 1 }],
    readBy: ["current-user", "jason-park", "carlos-mendez"],
    replyCount: 0,
  },
  {
    id: "inst-002",
    channelId: "installations",
    sender: m("jason-park"),
    source: "slack",
    type: "text",
    content: "I'll need the cabinet layout printed full-size for Monday. Sarah usually sends it — can someone confirm she's got the final v4?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T07:30:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "inst-003",
    channelId: "installations",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Sarah just posted v4 in the Smith channel. I'll get it printed at Staples this afternoon — 36x48 should work?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-24T08:30:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Jason Park"], count: 1 }],
    readBy: ["mike-thompson", "jason-park"],
    replyCount: 0,
  },
  {
    id: "inst-004",
    channelId: "installations",
    sender: m("carlos-mendez"),
    source: "slack",
    type: "text",
    content: "Mike — for Garcia demo Friday, are we saving the existing sink and dishwasher? The homeowners mentioned wanting to reuse the dishwasher in the laundry room",
    mentions: ["mike-thompson"],
    attachments: [],
    createdAt: "2026-03-24T09:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "mike-thompson"],
    replyCount: 0,
  },
  {
    id: "inst-005",
    channelId: "installations",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "Yeah, disconnect and set aside the dishwasher. Sink can go — they ordered a new Kraus undermount. Be careful with the granite though, demo around it, don't pry against it",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-24T09:15:00Z",
    isEdited: false,
    reactions: [{ emoji: "✅", users: ["Carlos Mendez"], count: 1 }],
    readBy: ["current-user", "carlos-mendez"],
    replyCount: 0,
  },
];

// ---------------------------------------------------------------------------
// Messages — DM with Sarah Chen (5 messages)
// ---------------------------------------------------------------------------

const dmSarahMessages: ChatMessage[] = [
  {
    id: "dms-001",
    channelId: "dm-sarah",
    sender: m("sarah-chen"),
    source: "slack",
    type: "text",
    content: "Hey Alex, quick q — the Smith backsplash. Lisa mentioned she saw a herringbone pattern she liked on Pinterest. Want me to mock it up or are we sticking with stack bond?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T13:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "dms-002",
    channelId: "dm-sarah",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Let's do a quick mockup of both and let her choose. Herringbone adds about $2/sf in labor but it's her kitchen",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T13:15:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["sarah-chen"],
    replyCount: 0,
  },
  {
    id: "dms-003",
    channelId: "dm-sarah",
    sender: m("sarah-chen"),
    source: "slack",
    type: "file",
    content: "Here's the swatch sample for the Dove White against the Calacatta Laza quartz. Colors play really nicely together in natural light",
    attachments: [
      {
        id: "att-040",
        name: "dove_white_calacatta_swatch.jpg",
        fileType: "image",
        url: "/files/dove-white-swatch.jpg",
        size: "1.4 MB",
        thumbnailUrl: "/thumbs/dove-white-swatch.jpg",
      },
    ],
    createdAt: "2026-03-23T14:30:00Z",
    isEdited: false,
    reactions: [{ emoji: "😍", users: ["Alex Rivera"], count: 1 }],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "dms-004",
    channelId: "dm-sarah",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "That looks amazing. Great pairing. Can you bring the physical sample to the site Thursday? Lisa wants to see it in her actual lighting",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T14:45:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["sarah-chen"],
    replyCount: 0,
  },
  {
    id: "dms-005",
    channelId: "dm-sarah",
    sender: m("sarah-chen"),
    source: "slack",
    type: "text",
    content: "Absolutely, I'll be there around 2pm. Also — Garcia design review is next Tuesday at 10, want me to prep the presentation?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-24T10:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: [],
    replyCount: 0,
  },
];

// ---------------------------------------------------------------------------
// Messages — DM with Mike Thompson (4 messages)
// ---------------------------------------------------------------------------

const dmMikeMessages: ChatMessage[] = [
  {
    id: "dmm-001",
    channelId: "dm-mike",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Mike — what's your crew availability look like for the first two weeks of April? I'm trying to map out the Garcia kitchen install timeline",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T11:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["mike-thompson"],
    replyCount: 0,
  },
  {
    id: "dmm-002",
    channelId: "dm-mike",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "Week of 3/31 is packed — finishing Smith plus the Garcia demo. Week of 4/7 I have a 3-man crew available Mon-Thu. That work?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T11:30:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "dmm-003",
    channelId: "dm-mike",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "That's tight but should work. Garcia lower cabinets Mon-Tue, uppers Wed-Thu. Then countertop template the following Monday. Sound doable?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T11:45:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["mike-thompson"],
    replyCount: 0,
  },
  {
    id: "dmm-004",
    channelId: "dm-mike",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "Yeah that's realistic. Only risk is if the electrician isn't done with the panel upgrade by then. Might want to check with Tom on his permit timeline",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T12:00:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Alex Rivera"], count: 1 }],
    readBy: ["current-user"],
    replyCount: 0,
  },
];

// ---------------------------------------------------------------------------
// Messages — DM with Lisa Johnson (6 messages)
// ---------------------------------------------------------------------------

const dmLisaMessages: ChatMessage[] = [
  {
    id: "dml-001",
    channelId: "dm-lisa",
    sender: m("lisa-johnson"),
    source: "kiptra",
    type: "text",
    content: "Hi Alex! Just checking in — when do you think the cabinets will be installed? My mom is visiting April 10 and I'd love to have the kitchen somewhat functional by then 😊",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T19:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "dml-002",
    channelId: "dm-lisa",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Hey Lisa! Great news — the cabinets arrived yesterday in perfect shape. We start installing the upper cabinets Monday and should have all cabinets done by Wednesday. After that we do the countertop measurement Thursday, and the countertops get fabricated and installed about 8-10 business days later. So by April 10 you should have cabinets, countertops, and a working sink. It'll look like a real kitchen again!",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T19:30:00Z",
    isEdited: false,
    reactions: [{ emoji: "❤️", users: ["Lisa Johnson"], count: 1 }],
    readBy: ["lisa-johnson"],
    replyCount: 0,
  },
  {
    id: "dml-003",
    channelId: "dm-lisa",
    sender: m("lisa-johnson"),
    source: "kiptra",
    type: "text",
    content: "That's amazing!! What about the backsplash? And the lighting you mentioned?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T19:45:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user"],
    replyCount: 0,
  },
  {
    id: "dml-004",
    channelId: "dm-lisa",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Backsplash goes in after countertops — probably April 8-9 timeframe. The under-cabinet LED lights (the ones you approved the change order for) get wired during cabinet install so those will be working right away. By the time your mom visits, the big stuff will be done. Backsplash might still be curing but it'll look beautiful",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-22T20:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["lisa-johnson"],
    replyCount: 0,
  },
  {
    id: "dml-005",
    channelId: "dm-lisa",
    sender: m("lisa-johnson"),
    source: "kiptra",
    type: "text",
    content: "Perfect! Also I saw a herringbone backsplash on Pinterest that I really love. Is it too late to change the pattern? Here's the link I saved",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-24T12:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: [],
    replyCount: 0,
  },
  {
    id: "dml-006",
    channelId: "dm-lisa",
    sender: m("lisa-johnson"),
    source: "kiptra",
    type: "text",
    content: "https://pinterest.com/pin/kitchen-herringbone-subway — something like this! Is it a lot more expensive?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-24T12:02:00Z",
    isEdited: false,
    reactions: [],
    readBy: [],
    replyCount: 0,
  },
];

// ---------------------------------------------------------------------------
// Messages — Group DM: Smith Kitchen Team (5 messages)
// ---------------------------------------------------------------------------

const gmSmithTeamMessages: ChatMessage[] = [
  {
    id: "gm-001",
    channelId: "gm-smith-team",
    sender: m("current-user"),
    source: "kiptra",
    type: "text",
    content: "Quick sync — Thursday install logistics. Mike your crew handles uppers, Jason stages the lowers in the garage. Sarah will be on-site at 2pm for the countertop template appointment. Questions?",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T16:00:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["sarah-chen", "mike-thompson", "jason-park"],
    replyCount: 0,
  },
  {
    id: "gm-002",
    channelId: "gm-smith-team",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "All good on my end. We'll start at 7am. Should have the uppers hung and leveled by noon if the walls are straight. Which they probably aren't lol",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T16:15:00Z",
    isEdited: false,
    reactions: [{ emoji: "😂", users: ["Jason Park", "Alex Rivera"], count: 2 }],
    readBy: ["current-user", "sarah-chen", "jason-park"],
    replyCount: 0,
  },
  {
    id: "gm-003",
    channelId: "gm-smith-team",
    sender: m("jason-park"),
    source: "slack",
    type: "text",
    content: "I'll be there at 6:30 to unload from the truck. Need anyone to help carry? Some of those 42\" uppers are heavy",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T16:30:00Z",
    isEdited: false,
    reactions: [],
    readBy: ["current-user", "mike-thompson", "sarah-chen"],
    replyCount: 0,
  },
  {
    id: "gm-004",
    channelId: "gm-smith-team",
    sender: m("mike-thompson"),
    source: "teams",
    type: "text",
    content: "I'll have Danny there early. Two guys can handle the unload. Jason, just make sure we have the filler strips and the crown moulding separated — don't want to hunt for them mid-install",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T16:45:00Z",
    isEdited: false,
    reactions: [{ emoji: "👍", users: ["Jason Park"], count: 1 }],
    readBy: ["current-user", "sarah-chen", "jason-park"],
    replyCount: 0,
  },
  {
    id: "gm-005",
    channelId: "gm-smith-team",
    sender: m("sarah-chen"),
    source: "slack",
    type: "text",
    content: "I'll bring the printed layout and the color samples for Lisa. She wants to see the backsplash options in person. See everyone Thursday!",
    mentions: [],
    attachments: [],
    createdAt: "2026-03-23T17:00:00Z",
    isEdited: false,
    reactions: [{ emoji: "✅", users: ["Alex Rivera"], count: 1 }],
    readBy: ["current-user", "mike-thompson", "jason-park"],
    replyCount: 0,
  },
];

// ---------------------------------------------------------------------------
// All Messages — keyed by channelId
// ---------------------------------------------------------------------------

export const MOCK_MESSAGES: Record<string, ChatMessage[]> = {
  "proj-smith-kitchen": smithKitchenMessages,
  "proj-johnson-masterbath": johnsonBathMessages,
  "proj-garcia-fullremodel": garciaMessages,
  "general": generalMessages,
  "submittals": submittalsMessages,
  "installations": installationsMessages,
  "dm-sarah": dmSarahMessages,
  "dm-mike": dmMikeMessages,
  "dm-lisa": dmLisaMessages,
  "gm-smith-team": gmSmithTeamMessages,
};

// ---------------------------------------------------------------------------
// Threads — keyed by root message ID
// ---------------------------------------------------------------------------

export const MOCK_THREADS: Record<string, ChatMessage[]> = {
  // KraftMaid submittal thread in #proj-smith-kitchen (root: sk-005)
  "sk-005": [
    {
      id: "sk-005-r1",
      channelId: "proj-smith-kitchen",
      threadId: "sk-005",
      sender: m("current-user"),
      source: "kiptra",
      type: "text",
      content: "W3636. The 30\" was too tight with the filler panel. Updated the submittal",
      mentions: [],
      attachments: [],
      createdAt: "2026-03-22T13:35:00Z",
      isEdited: false,
      reactions: [],
      readBy: ["sarah-chen"],
      replyCount: 0,
    },
    {
      id: "sk-005-r2",
      channelId: "proj-smith-kitchen",
      threadId: "sk-005",
      sender: m("sarah-chen"),
      source: "slack",
      type: "text",
      content: "Got it. That changes the filler from 3\" to 1.5\". I'll update the elevation drawing",
      mentions: [],
      attachments: [],
      createdAt: "2026-03-22T13:50:00Z",
      isEdited: false,
      reactions: [],
      readBy: ["current-user"],
      replyCount: 0,
    },
    {
      id: "sk-005-r3",
      channelId: "proj-smith-kitchen",
      threadId: "sk-005",
      sender: m("david-kim"),
      source: "teams",
      type: "text",
      content: "FYI the W3636 is $45 more than the W3630. Updated the PO — new cabinet total is $28,545",
      mentions: [],
      attachments: [],
      createdAt: "2026-03-22T14:00:00Z",
      isEdited: false,
      reactions: [],
      readBy: ["current-user", "sarah-chen"],
      replyCount: 0,
    },
    {
      id: "sk-005-r4",
      channelId: "proj-smith-kitchen",
      threadId: "sk-005",
      sender: m("current-user"),
      source: "kiptra",
      type: "text",
      content: "No problem, $45 is nothing. Thanks for the quick update David",
      mentions: [],
      attachments: [],
      createdAt: "2026-03-22T14:15:00Z",
      isEdited: false,
      reactions: [{ emoji: "👍", users: ["David Kim"], count: 1 }],
      readBy: ["sarah-chen", "david-kim"],
      replyCount: 0,
    },
  ],

  // Tile selection thread in #proj-johnson-masterbath (root: jb-003)
  "jb-003": [
    {
      id: "jb-003-r1",
      channelId: "proj-johnson-masterbath",
      threadId: "jb-003",
      sender: m("rachel-torres"),
      source: "slack",
      type: "text",
      content: "I'd lean Palazzo for the aesthetic. The veining is much more natural-looking. 3 weeks is doable if we order today — we don't need it until mid-April",
      mentions: [],
      attachments: [],
      createdAt: "2026-03-22T12:00:00Z",
      isEdited: false,
      reactions: [],
      readBy: ["current-user", "david-kim"],
      replyCount: 0,
    },
    {
      id: "jb-003-r2",
      channelId: "proj-johnson-masterbath",
      threadId: "jb-003",
      sender: m("current-user"),
      source: "kiptra",
      type: "text",
      content: "Agreed on the Palazzo. The $2.65/sf premium is worth it for a master bath — this is the room they'll see every morning. David, lock it in",
      mentions: ["david-kim"],
      attachments: [],
      createdAt: "2026-03-22T12:30:00Z",
      isEdited: false,
      reactions: [],
      readBy: ["david-kim", "rachel-torres"],
      replyCount: 0,
    },
    {
      id: "jb-003-r3",
      channelId: "proj-johnson-masterbath",
      threadId: "jb-003",
      sender: m("david-kim"),
      source: "teams",
      type: "text",
      content: "Done. 22 boxes (176 sf with 10% waste). Order placed, ETA April 11. Confirmation incoming",
      mentions: [],
      attachments: [],
      createdAt: "2026-03-22T13:00:00Z",
      isEdited: false,
      reactions: [{ emoji: "✅", users: ["Alex Rivera", "Rachel Torres"], count: 2 }],
      readBy: ["current-user", "rachel-torres"],
      replyCount: 0,
    },
  ],

  // Material backorder thread in #proj-garcia-fullremodel (root: gr-004)
  "gr-004": [
    {
      id: "gr-004-r1",
      channelId: "proj-garcia-fullremodel",
      threadId: "gr-004",
      sender: m("current-user"),
      source: "kiptra",
      type: "text",
      content: "This is a problem. 6 days past our install date. David — what alternatives do we have in the Caesarstone calacatta family?",
      mentions: ["david-kim"],
      attachments: [],
      createdAt: "2026-03-22T10:10:00Z",
      isEdited: false,
      reactions: [],
      readBy: ["david-kim", "sarah-chen"],
      replyCount: 0,
    },
    {
      id: "gr-004-r2",
      channelId: "proj-garcia-fullremodel",
      threadId: "gr-004",
      sender: m("david-kim"),
      source: "teams",
      type: "text",
      content: "5141 Frosty Carrina is in stock locally, 5153 Vanilla Noir is also available but very different look. Recommend the 5141 — closest match to what the Garcias approved",
      mentions: [],
      attachments: [],
      createdAt: "2026-03-22T10:40:00Z",
      isEdited: false,
      reactions: [],
      readBy: ["current-user", "sarah-chen"],
      replyCount: 0,
    },
    {
      id: "gr-004-r3",
      channelId: "proj-garcia-fullremodel",
      threadId: "gr-004",
      sender: m("sarah-chen"),
      source: "slack",
      type: "text",
      content: "5141 is a solid swap. Very similar colorway, just slightly cooler undertones. I'll send the Garcias a side-by-side comparison with the sample photos from Caesarstone's site",
      mentions: [],
      attachments: [],
      createdAt: "2026-03-22T11:15:00Z",
      isEdited: false,
      reactions: [{ emoji: "👍", users: ["Alex Rivera", "David Kim"], count: 2 }],
      readBy: ["current-user", "david-kim"],
      replyCount: 0,
    },
  ],
};

// ---------------------------------------------------------------------------
// Integration Status
// ---------------------------------------------------------------------------

export const MOCK_INTEGRATIONS: ChatIntegration[] = [
  {
    platform: "slack",
    status: "connected",
    workspaceName: "Rivera Remodeling",
    connectedAt: "2025-11-15T10:00:00Z",
    channelsSynced: 4,
    lastSyncAt: "2026-03-24T17:28:00Z",
    connectedBy: "Alex Rivera",
  },
  {
    platform: "teams",
    status: "connected",
    workspaceName: "Rivera Design Group",
    connectedAt: "2025-12-01T14:00:00Z",
    channelsSynced: 2,
    lastSyncAt: "2026-03-24T17:25:00Z",
    connectedBy: "Alex Rivera",
  },
];

// ---------------------------------------------------------------------------
// Helper Functions
// ---------------------------------------------------------------------------

export function getChannelMessages(channelId: string): ChatMessage[] {
  return MOCK_MESSAGES[channelId] ?? [];
}

export function getThreadReplies(messageId: string): ChatMessage[] {
  return MOCK_THREADS[messageId] ?? [];
}

export function getChannel(channelId: string): ChatChannel | undefined {
  return MOCK_CHANNELS.find((c) => c.id === channelId);
}

export function getMember(memberId: string): ChatMember | undefined {
  return MOCK_MEMBERS.find((m) => m.id === memberId);
}

export function formatMessageTime(isoString: string): string {
  const date = new Date(isoString);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays === 0) {
    return date.toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    });
  }

  if (diffDays === 1) {
    return "Yesterday";
  }

  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
  });
}

export function getUnreadTotal(): number {
  return MOCK_CHANNELS.reduce((sum, channel) => sum + channel.unreadCount, 0);
}
